# Generated by Django 5.0.6 on 2024-05-15 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('criteria', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('lt', '<'), ('gt', '>'), ('lte', '<='), ('gte', '>='), ('eq', '==')], max_length=3)),
                ('comparison_value', models.FloatField()),
                ('frequency', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('status', models.CharField(default='Active', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
